### ISSUE TITLE
i have this error

### ISSUE THREAD

**Issue by OoAnikioO** [Time-Travel-Rephotography/Time-Travel-Rephotography.github.io#21]
python projector.py 'dataset/Abraham Lincoln_01.png' --gaussian 0.75 --log_dir log/ --results_dir results/ --spectral_sensitivity b --encoder_ckpt checkpoint/encoder/checkpoint_b.pt
C:\Users\Papa\Downloads\Conda\envs\rephotography\lib\site-packages\torch\utils\cpp_extension.py:209: UserWarning: Error checking compiler version for cl: [WinError 2] Le fichier spécifié est introuvable
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
Information : impossible de trouver des fichiers pour le(s) modèle(s) spécifié(s).
Traceback (most recent call last):
  File "projector.py", line 25, in <module>
    from model import Generator
  File "C:\Users\Papa\Downloads\Conda\Moi\time\model.py", line 12, in <module>
    from op import FusedLeakyReLU, fused_leaky_relu, upfirdn2d
  File "C:\Users\Papa\Downloads\Conda\Moi\time\op\__init__.py", line 1, in <module>
    from .fused_act import FusedLeakyReLU, fused_leaky_relu
  File "C:\Users\Papa\Downloads\Conda\Moi\time\op\fused_act.py", line 10, in <module>
    fused = load(
  File "C:\Users\Papa\Downloads\Conda\envs\rephotography\lib\site-packages\torch\utils\cpp_extension.py", line 670, in load
    return _jit_compile(
  File "C:\Users\Papa\Downloads\Conda\envs\rephotography\lib\site-packages\torch\utils\cpp_extension.py", line 857, in _jit_compile
    _write_ninja_file_and_build(
  File "C:\Users\Papa\Downloads\Conda\envs\rephotography\lib\site-packages\torch\utils\cpp_extension.py", line 907, in _write_ninja_file_and_build
    _write_ninja_file(
  File "C:\Users\Papa\Downloads\Conda\envs\rephotography\lib\site-packages\torch\utils\cpp_extension.py", line 1194, in _write_ninja_file
    cl_paths = subprocess.check_output(['where',
  File "C:\Users\Papa\Downloads\Conda\envs\rephotography\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Papa\Downloads\Conda\envs\rephotography\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

**Comment by StephenHnilica** [comment]
I have the same error.

**Comment by BillarySquintin** [comment]
Ok I've figured out the solution. This issue is related to the files not being able to be retrieved from Google Drive.

In the "Download models" cell, you have to make a shortcut of the models in your own GDrive and copy them into their respective folders in the Colab instance storage.

The missing model that's causing this issue is the last one in that cell, https://drive.google.com/uc?id=1vwm4BcAKISQgcJLvTUcvesk73UIYdDMF. Because that model isn't available, the faces can't be parsed & there's no image for OpenCV to resize.

You have to copy that model to "Time-Travel-Rephotography/third_party/face_parsing/res/cp/"
