### ISSUE TITLE
Huggingface error

### ISSUE THREAD

**Issue by Excurl** [Time-Travel-Rephotography/Time-Travel-Rephotography.github.io#29]
Traceback (most recent call last):
  File "app.py", line 79, in <module>
    main()
  File "app.py", line 56, in main
    torch.cuda.init()
  File "/home/user/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 198, in init
    _lazy_init()
  File "/home/user/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 229, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

**Comment by Excurl** [comment]
can you fix the error in huggingface please

**Comment by Excurl** [comment]
PLS FIX FENGG

**Comment by xstrauss** [comment]
Is there a Huggingface space link? Please share 🙏🙏

**Comment by Excurl** [comment]
here is it https://huggingface.co/spaces/feng2022/Time-TravelRephotography

**Comment by xstrauss** [comment]
> here is it https://huggingface.co/spaces/feng2022/Time-TravelRephotography

But it's not working?
Runtime error, it says.
